-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 10:43:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `COD_PRODUCTO`  DECIMAL(65,2) NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `DESCRIPCION_PRODUCTO` VARCHAR(35) NULL,
  `PRECIO` INT NOT NULL,
  `CANTIDAD` DECIMAL NOT NULL,
  `FOTO` VARCHAR(100) NULL,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_PRODUCTO`));


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `COD_CATEGORIA` DECIMAL(65,2) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`COD_CATEGORIA`));


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA_X_PRODUCTO`
-- -----------------------------------COD_PRODUCTO------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA_X_PRODUCTO` (
  `CATEGORIA_COD_CATEGORIA` DECIMAL(65,2) NOT NULL,
  `PRODUCTO_COD_PRODUCTO` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`PRODUCTO_COD_PRODUCTO`, `CATEGORIA_COD_CATEGORIA`),
  CONSTRAINT `fk_CATEGORIA_X_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_COD_CATEGORIA`)
    REFERENCES `mydb`.`CATEGORIA` (`COD_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_X_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_COD_PRODUCTO`)
    REFERENCES `mydb`.`PRODUCTO` (`COD_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_CATEGORIA_X_PRODUCTO_CATEGORIA1_idx` ON `mydb`.`CATEGORIA_X_PRODUCTO` (`CATEGORIA_COD_CATEGORIA` ASC);

CREATE INDEX `fk_CATEGORIA_X_PRODUCTO_PRODUCTO1_idx` ON `mydb`.`CATEGORIA_X_PRODUCTO` (`PRODUCTO_COD_PRODUCTO` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `COD_PEDIDO` DECIMAL(65,2) NOT NULL,
  `FECHA` DATETIME NOT NULL,
  `PAIS` VARCHAR(45) NULL,
  `DEPARTAMENTO` VARCHAR(45) NULL,
  `CIUDAD` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `TELEFONO_FIJIO` VARCHAR(15) NULL,
  `TELEFONO_CELULAR` VARCHAR(10) NULL,
  PRIMARY KEY (`COD_PEDIDO`));


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_PEDIDO` (
  `CANTIDAD_PRODUCTO`  DECIMAL(65,2) NOT NULL,
  `PRODUCTO_COD_PRODUCTO` DECIMAL(65,2) NOT NULL,
  `PEDIDO_COD_PEDIDO` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`PRODUCTO_COD_PRODUCTO`, `PEDIDO_COD_PEDIDO`),
  CONSTRAINT `fk_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_COD_PRODUCTO`)
    REFERENCES `mydb`.`PRODUCTO` (`COD_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_COD_PEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`COD_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_PEDIDO_PRODUCTO1_idx` ON `mydb`.`DETALLE_PEDIDO` (`PRODUCTO_COD_PRODUCTO` ASC);

CREATE INDEX `fk_DETALLE_PEDIDO_PEDIDO1_idx` ON `mydb`.`DETALLE_PEDIDO` (`PEDIDO_COD_PEDIDO` ASC);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


CREATE TABLE IF NOT EXISTS `mydb`.`CODIGO_TABLA` (
	`COD_CATEGORIA`  DECIMAL(65,2) NOT NULL,
	`COD_PRODUCTO` DECIMAL(65,2) NOT NULL,
	`COD_PEDIDO` DECIMAL(65,2) NOT NULL
);

INSERT INTO `mydb`.`user`
(`username`,
`email`,
`password`)
VALUES
('admin',
'admin@admin.com',
'admin');

ALTER PRODUCTO ALTER COLUMN FOTO VARCHAR (500) NOT NULL


