package entity;
// Generated 6/02/2018 12:15:25 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPrograma generated by hbm2java
 */
@Entity
@Table(name="TB_PROGRAMA"
    ,schema="SYSTEM"
)
public class TbPrograma  implements java.io.Serializable {


     private BigDecimal idPrograma;
     private String descripcion;
     private boolean estado;
     private String creadopor;
     private Date creadoen;
     private String modificadopor;
     private Date modificadoen;

    public TbPrograma() {
    }

	
    public TbPrograma(BigDecimal idPrograma, String descripcion, boolean estado, String creadopor) {
        this.idPrograma = idPrograma;
        this.descripcion = descripcion;
        this.estado = estado;
        this.creadopor = creadopor;
    }
    public TbPrograma(BigDecimal idPrograma, String descripcion, boolean estado, String creadopor, Date creadoen, String modificadopor, Date modificadoen) {
       this.idPrograma = idPrograma;
       this.descripcion = descripcion;
       this.estado = estado;
       this.creadopor = creadopor;
       this.creadoen = creadoen;
       this.modificadopor = modificadopor;
       this.modificadoen = modificadoen;
    }
   
     @Id 

    
    @Column(name="ID_PROGRAMA", unique=true, nullable=false, precision=10, scale=0)
    public BigDecimal getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(BigDecimal idPrograma) {
        this.idPrograma = idPrograma;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", nullable=false, precision=1, scale=0)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="CREADOPOR", nullable=false, length=50)
    public String getCreadopor() {
        return this.creadopor;
    }
    
    public void setCreadopor(String creadopor) {
        this.creadopor = creadopor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREADOEN", length=7)
    public Date getCreadoen() {
        return this.creadoen;
    }
    
    public void setCreadoen(Date creadoen) {
        this.creadoen = creadoen;
    }

    
    @Column(name="MODIFICADOPOR", length=50)
    public String getModificadopor() {
        return this.modificadopor;
    }
    
    public void setModificadopor(String modificadopor) {
        this.modificadopor = modificadopor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFICADOEN", length=7)
    public Date getModificadoen() {
        return this.modificadoen;
    }
    
    public void setModificadoen(Date modificadoen) {
        this.modificadoen = modificadoen;
    }




}


