package entity;
// Generated Sep 7, 2015 9:39:22 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="PROFESOR"
    ,schema="SYSTEM"
)
public class Profesor  implements java.io.Serializable {


     private BigDecimal id;
     private Departamento departamento;
     private String nombre;
     private String correo;
     private String nacimiento;
     private String telefono;
     private String direccion;
     //private BigDecimal idDepartamento;

    public Profesor() {
    }

	
    public Profesor(BigDecimal id, Departamento departamento) {
        this.id = id;
        this.departamento = departamento;
    }
    public Profesor(BigDecimal id, Departamento departamento, String nombre, String correo, String nacimiento, String telefono, String direccion) {
       this.id = id;
       this.departamento = departamento;
       this.nombre = nombre;
       this.correo = correo;
       this.nacimiento = nacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    @Id  
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTAMENTO", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="NOMBRE", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CORREO", length=80)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="NACIMIENTO", length=20)
    public String getNacimiento() {
        return this.nacimiento;
    }
    
    public void setNacimiento(String nacimiento) {
        this.nacimiento = nacimiento;
    }

    
    @Column(name="TELEFONO", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="DIRECCION", length=40)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

   /* public BigDecimal getIdDepartamento() {
        return idDepartamento;
    }

    public void setIdDepartamento(BigDecimal idDepartamento) {
        this.idDepartamento = idDepartamento;
    }*/
    




}


